Cald 014 boilers mongo db
Fdobboletta/CaldAR-BackEnd pull request #10
Opened 2020-11-29 22:10 UTC by martumoser

2020-11-30 12:18 UTC, Fdobboletta requested changes
Solamente te dejo un cambio menor para simplificar el codigo (y como buena practica). Esas cosas con el tiempo te van a ir saliendo automaticas jaja.
Muy buen trabajo Marti!

2020-11-30 12:18 UTC, Fdobboletta commented on src/controllers/boilersController.js
> +    if(!req.body.description || !req.body.boilerType || !req.body.maintenance_period || !req.body.hour_maintenance_cost || !req.body.hour_eventual_cost) {
Ya que esto se repite igual que en el "CREATE". Podrias hacer al principio del archivo una constante, ejemplo:

`const emptyAttribute = !req.body.description || !req.body.boilerType || !req.body.maintenance_period || !req.body.hour_maintenance_cost || !req.body.hour_eventual_cost`

Y despues haces `if (emptyAttribute) {res.status(400).send ({msg: "Content can not be empty"}); return;}` tanto aca como en el create de arriba

2020-11-30 12:18 UTC, Fdobboletta commented on src/controllers/boilersController.js
> +// Get all Boilers with a specific attribute (boilerType)
Esto por ahora esta bien, despues cuando hagamos el link entre esta tabla y el boilerType le vamos a tener que hacer algun retoque

2020-12-01 11:49 UTC, martumoser commented on src/controllers/boilersController.js
> +    if(!req.body.description || !req.body.boilerType || !req.body.maintenance_period || !req.body.hour_maintenance_cost || !req.body.hour_eventual_cost) {
Cuando la quise agregar al principio del archivo me tiró de error que req no estaba definido (ReferenceError: req is not defined) ) asi que cree la constante dentro de la función create y update.

2020-12-01 12:20 UTC, Fdobboletta approved these changes
Excelente

2020-12-01 12:21 UTC, merged