CALD-022-Technicians-Validations
Fdobboletta/CaldAR-BackEnd pull request #17
Opened 2020-12-08 07:02 UTC by svillav

2020-12-08 12:59 UTC, Fdobboletta requested changes
Ahi dejo algunas sugerencias

2020-12-08 12:59 UTC, Fdobboletta commented on src/controllers/technicianController.js
> +  if(!capabilities) {
Guarda aca que se te fueron un par de espacios de mas jajaja

2020-12-08 12:59 UTC, Fdobboletta commented on src/controllers/technicianController.js
> +  Technicians.findByIdAndRemove(req.params.id, { useFindAndModify: false })
Al borrar el Technician deberiamos tambien borrar todos los appointments que tengan el id de este Technician en el campo "Technician" de la entidad Appointments

2020-12-08 12:59 UTC, Fdobboletta commented on src/controllers/technicianController.js
> +      res.send(data);
Agregemos un status(200) cuando los datos salen de forma exitosa

2020-12-08 20:05 UTC, svillav commented on src/controllers/technicianController.js
> +  if(!capabilities) {
No entendí qué tengo que corregir, la indentación?

2020-12-09 02:30 UTC, Fdobboletta commented on src/controllers/technicianController.js
> +  if(!capabilities) {
Me aparecen 2 lineas en blanco entre el if y el res.status

2020-12-10 17:11 UTC, closed without merging